# Setup based off of https://github.com/Fantomas42/django-tagging/

language: python
python:
  - 3.8
services:
  - postgresql
  - mysql
env:
  - DJANGO=3.1 DATABASE_ENGINE=sqlite
  - DJANGO=3.1 DATABASE_ENGINE=postgres
  - DJANGO=3.1 DATABASE_ENGINE=mysql
install:
  - pip3 install -r requirements_dev.txt
  - pip3 install -e .
  - export DJANGO_SETTINGS_MODULE=subscriptions.tests.settings && django-admin makemigrations subscriptions tests && django-admin migrate
  - sh -c "if [ '$DATABASE_ENGINE' = 'postgres' ]; then pip install psycopg2; psql -c 'create database subscriptions;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_ENGINE' = 'mysql' ]; then pip install mysqlclient; mysql -e 'create database subscriptions CHARACTER SET utf8 COLLATE utf8_general_ci;'; mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql; fi"
script:
  - pytest
