# Generated by Django 3.1 on 2020-08-29 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_manager_name': 'subscriptions',
                'unique_together': {('subscriber', 'provider', 'content_type')},
            },
            managers=[
                ('subscriptions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HiddenContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='hidden', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'content_type', 'object_id')},
            },
        ),
    ]
